/*
 * Payment API   
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.antom.request.consult;

import com.antom.request.AlipayRequest;
import com.antom.response.AlipayResponse;
import com.antom.model.PayConsultRequest;
import com.antom.model.PayConsultResponse;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class DefaultApi {

    public static final String API_VERSION = "1";

    protected String baseURL;

    /**
    * default constructor in {@link com.antom.request.consult package}.
    * @param client {@link Client } (required)
    */
    public DefaultApi(Client client) {
        super(client);
        this.baseURL = createBaseURL("https://open-sea-global.alipay.com/ams/api/v1/payments");
    }

    /**
    * default constructor in {@link com.antom.request.consult package}.
    * Please use this constructor only if you would like to pass along your own url for routing or testing purposes. The latest API version is defined in this class as a constant.
    * @param client {@link Client } (required)
    * @param baseURL {@link String } (required)
    */
    public DefaultApi(Client client, String baseURL) {
        super(client);
        this.baseURL = baseURL;
    }

    public PayConsultResponse consultPayment throws ApiException, IOException {
        return consultPayment);
    }

    public PayConsultResponse consultPayment throws ApiException, IOException {

        String requestBody = payConsultRequest.toJson();
        Resource resource = new Resource(this, this.baseURL + "/consult", null);
        String jsonResult = resource.request(requestBody, requestOptions, ApiConstants.HttpMethod.POST, null);
        return PayConsultResponse.fromJson(jsonResult);
    }
}
