/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Amount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Amount {

  /**
   * The transaction currency that is specified in the contract. A 3-letter currency code that
   * follows the ISO 4217 standard. More information: Maximum length: 3 characters
   */
  private String currency;

  /**
   * The amount to charge as a positive integer in the smallest currency unit. (That is, 100 cents
   * to charge $1.00, or 100 to charge JPY 100, a 0-decimal currency). Note: For details about the
   * smallest currency unit, see Smallest unit of the currency. More information: Value range: 1 -
   * unlimited
   */
  private String value;
}
