/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import io.swagger.annotations.ApiModel;
import lombok.*;

/** The payment amount that the merchant requests to receive in the order currency. */
@ApiModel(
    description = "The payment amount that the merchant requests to receive in the order currency.")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Amount {

  /** The 3-letter currency code that follows the ISO 4217 standard. */
  private String currency;

  /**
   * The value of the amount as a positive integer in the smallest currency unit. For example, if
   * the currency is USD and the amount is $1.00, set the value of this parameter to 100; or if the
   * currency is JPY and the amount is ￥1, set the value of this parameter to 1.
   */
  private String value;
}
