/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** BrowserInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BrowserInfo {

  /**
   * The accept header of the user&#39;s browser. More information: Maximum length: 2048 characters
   */
  private String acceptHeader;

  /**
   * Indicates whether the user&#39;s browser is able to run Java. Valid values are: true: indicates
   * that the user&#39;s browser is able to run Java. false: indicates that the user&#39;s browser
   * is unable to run Java. The same applies when the value is empty or you do not specify this
   * parameter.
   */
  private Boolean javaEnabled;

  /**
   * Indicates whether the user&#39;s browser is able to run Java. Valid values are: true: indicates
   * that the user&#39;s browser is able to run JavaScript. false: indicates that the user&#39;s
   * browser is unable to run JavaScript. The same applies when the value is empty or you do not
   * specify this parameter.
   */
  private Boolean javaScriptEnabled;

  /**
   * The language of the user&#39;s browser. The value is obtained by using the browser&#39;s
   * navigator.language property (as defined in IETF BCP 47). More information: Maximum length: 32
   * characters
   */
  private String language;

  /**
   * The user agent of the user&#39;s browser. Specify this parameter when one of the following
   * conditions is met: You require risk control. The value of paymentMethodType is BLIK and you
   * collect the information of blikCode. Providing this information helps to increase the accuracy
   * of anti-money laundering and fraud detection, and increase payment success rates. More
   * information: Maximum length: 2048 characters
   */
  private String userAgent;
}
