/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Buyer */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Buyer {

  /**
   * The unique ID to identify the buyer. Specify this parameter when one of the following
   * conditions is met: When you require risk control. When the value of paymentMethodType is CARD.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates. More information: Maximum length: 64 characters
   */
  private String referenceBuyerId;

  private UserName buyerName;

  /**
   * The mobile phone number of the buyer. Specify this parameter when one of the following
   * conditions is met: When you require risk control. When the value of paymentMethodType is CARD.
   * When the value of paymentMethodType is KONBINI, BANKTRANSFER_PAYEASY, or ONLINEBANKING_PAYEASY
   * and you need to collect the phone number during the payment process. When the value of
   * paymentMethodType is BANCOMATPAY and you need to collect the phone number bound to the Bancomat
   * Pay account during the payment process. When the value of paymentMethodType is OVO and you need
   * to collect the phone number bound to the OVO account during the payment process. Here are the
   * guidelines for the phone number format: Begin with the number 08 or 8, such as 085775716613 or
   * 85775716613. Include the area code without a plus sign and the length should be between 9 and
   * 12 digits, such as 62085775716613 or 6285775716613. Omit the area code, such as 085775716613 or
   * 85775716613. Providing this information helps to increase the accuracy of anti-money laundering
   * and fraud detection, and increase payment success rates. More information: Maximum length: 24
   * characters
   */
  private String buyerPhoneNo;

  /**
   * The email of the buyer. Specify this parameter when one of the following conditions is met:
   * When you require risk control. When the value of paymentMethodType is CARD. The value of
   * paymentMethodType is KONBINI, BANKTRANSFER_PAYEASY, or ONLINEBANKING_PAYEASY and you collect
   * this information during the payment process. Providing this information helps to increase the
   * accuracy of anti-money laundering and fraud detection, and increase payment success rates. More
   * information: Maximum length: 64 characters
   */
  private String buyerEmail;

  /**
   * The time when the buyer registered your account. Specify this parameter if you require risk
   * control. Providing this information helps to increase the accuracy of anti-money laundering and
   * fraud detection, and increase payment success rates. More information: Maximum length: 64
   * characters The value follows the ISO 8601 standard format. For example,
   * \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String buyerRegistrationTime;

  private Boolean isAccountVerified;

  private Integer successfulOrderCount;
}
