/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Buyer */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Buyer {

  /** The unique ID to identify the buyer. */
  private String referenceBuyerId;

  private UserName buyerName;

  private String buyerPhoneNo;

  private String buyerEmail;

  private String buyerRegistrationTime;

  private Boolean isAccountVerified;

  private Integer successfulOrderCount;
}
