/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Discount */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Discount {

  /** The discount tag is displayed as a superscript next to the discount name. */
  private String discountTag;

  /** The discount name displayed in the default language. */
  private String discountName;

  private Amount estimateSavingsAmount;
}
