/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import io.swagger.annotations.ApiModel;
import lombok.*;

/** Information about the environment where the order is placed, such as the device information. */
@ApiModel(
    description =
        "Information about the environment where the order is placed, such as the device information. ")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Env {

  private TerminalType terminalType;

  private OsType osType;

  /** The user agent. */
  private String userAgent;

  /** Token identifier of the device. */
  private String deviceTokenId;

  /** IP address of the client device. */
  private String clientIp;

  /** The cookie ID of the buyer. */
  private String cookieId;

  private String storeTerminalId;

  private String storeTerminalRequestTime;

  private BrowserInfo browserInfo;

  private String colorDepth;

  private String screenHeight;

  private String screenWidth;

  private String timeZoneOffset;

  private Integer deviceBrand;

  private String deviceModel;

  private String deviceLanguage;

  private String deviceId;
}
