/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Gaming */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Gaming {

  /** Game name. More information: Maximum length: 128 characters */
  private String gameName;

  /**
   * Name or ID of the user whose gaming account is topped up. More information: Maximum length: 128
   * characters
   */
  private String toppedUpUser;

  /** Email of the user. More information: Maximum length: 64 characters */
  private String toppedUpEmail;

  /** Phone number of the user. More information: Maximum length: 32 characters */
  private String toppedUpPhoneNo;
}
