/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** InterestFree */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InterestFree {

  /** Issuing banks or financial institutions that offer interest-free installment plans. */
  private String provider;

  /** The promotion expiration time. */
  private String expireTime;

  /** The number of interest-free installments. */
  private Integer installmentFreeNums;

  private Amount minPaymentAmount;

  private Amount maxPaymentAmount;

  /**
   * The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer
   * is completely interest-free, while the value between 0-100% indicates partial interest-free.
   */
  private Integer freePercentage;
}
