/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Leg */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Leg {

  /**
   * Time of departure for this leg of the trip. More information: The value follows the ISO 8601
   * standard format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String departureTime;

  /**
   * Time of arrival for this leg of the trip. More information: The value follows the ISO 8601
   * standard format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String arrivalTime;

  private Address departureAddress;

  private Address arrivalAddress;

  private String carrierName;

  /**
   * Code for the carrier for this leg of the trip. More information: Maximum length: 64 characters
   */
  private String carrierNo;

  private ClassType classType;

  /**
   * IATA code for the originating airport for this leg of the trip. More information: Maximum
   * length: 8 characters
   */
  private String departureAirportCode;

  /**
   * IATA code for the destination airport for this leg of the trip. More information: Maximum
   * length: 8 characters
   */
  private String arrivalAirportCode;
}
