/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Merchant */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Merchant {

  /**
   * The ID to identify the merchant that directly provides services or goods to the customer. More
   * information: Maximum length: 32 characters
   */
  private String referenceMerchantId;

  /**
   * The secondary merchant category code, which is a 4-digit number listed in MCC codes. Note:
   * Specify this field if you have the information. Providing this information helps to increase
   * the accuracy of anti-money laundering and fraud detection, and increase payment success rates.
   * More information: Maximum length: 32 characters
   */
  private String merchantMCC;

  /**
   * The merchant name. Note: Specify this field if you have the information. Providing this
   * information helps to increase the accuracy of anti-money laundering and fraud detection, and
   * increase payment success rates. More information: Maximum length: 256 characters
   */
  private String merchantName;

  /**
   * The merchant name to be displayed. Note: Specify this field if you have the information.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates. More information: Maximum length: 64 characters
   */
  private String merchantDisplayName;

  private Address merchantAddress;

  /**
   * Merchant registration date. Note: Specify this field if you have the information. Providing
   * this information helps to increase the accuracy of anti-money laundering and fraud detection,
   * and increase payment success rates. More information: The value follows the ISO 8601 standard
   * format. For example, \&quot;2019-11-27T12:01:01+08:00\&quot;.
   */
  private String merchantRegisterDate;

  private Store store;

  private MerchantType merchantType;
}
