/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Passenger */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Passenger {

  private UserName passengerName;

  /** The email of the passenger. More information: Maximum length: 64 characters */
  private String passengerEmail;

  /** The mobile phone number of the passenger. More information: Maximum length: 32 characters */
  private String passengerPhoneNo;
}
