/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.util.Map;
import lombok.*;

/** PaymentMethod */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentMethod {

  /**
   * The payment method type that is included in payment method options. By specifying the value of
   * this parameter, you can receive the cashier URL of the specified payment method returned by
   * Antom. See Payment methods to check the valid values. More information: Maximum length: 64
   * characters
   */
  private String paymentMethodType;

  /**
   * The unique ID that is used to identify a payment method. The value of this parameter is that of
   * cardToken obtained from the notifyPayment or inquiryPayment API. Note: Specify this parameter
   * when the value of paymentMethodType is CARD. More information: Maximum length: 128 characters
   */
  private String paymentMethodId;

  /**
   * Additional information required for some specific payment methods. Note: Specify this parameter
   * when the value of paymentMethodType is BLIK, P24 , CARD, MERCADOPAGO_BR, MERCADOPAGO_MX,
   * MERCADOPAGO_CL, MERCADOPAGO_PE, ONLINEBANKING_FPX, PAGALEVE ,GOOGLEPAY or APPLEPAY.
   */
  private Map<String, Object> paymentMethodMetaData;

  /**
   * The unique ID to identify a buyer. Note: Specify this field if you have the information.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates.
   */
  private String customerId;

  /**
   * Extended information. Note: Specify this field if you need to use the extended information.
   * More information: Maximum length: 2048 characters
   */
  private String extendInfo;

  private Boolean requireIssuerAuthentication;
}
