/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PaymentFactor */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentFactor {

  /**
   * The presentation mode chosen by the merchant to display the payment methods on the cashier
   * page. Valid values are:
   */
  private String presentmentMode;

  private String isPaymentEvaluation;

  private String inStorePaymentScenario;

  private String captureMode;

  private Boolean isAuthorization;
}
