/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PaymentResultInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentResultInfo {

  private String cardNo;

  private String cardBrand;

  private String cardToken;

  private String issuingCountry;

  private String funding;

  private String paymentMethodRegion;

  private String threeDSResult;

  private String avsResultRaw;

  private String cvvResultRaw;

  private String networkTransactionId;

  private String creditPayPlan;

  private String cardholderName;

  private String cardBin;

  private String lastFour;

  private String expiryMonth;

  private String expiryYear;
}
