/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.*;

/** Plan */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Plan {

  /** The interest rate the customer is charged on the installments. */
  private String interestRate;

  private Amount minInstallmentAmount;

  private Amount maxInstallmentAmount;

  /** The number of installment payments. The valid value is from 2 to 12. */
  private Integer installmentNum;

  /** The interval of each installment payment. The valid value is MONTH. */
  public enum IntervalEnum {
    MONTH("MONTH");

    private String value;

    IntervalEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IntervalEnum fromValue(String value) {
      for (IntervalEnum b : IntervalEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  /** The interval of each installment payment. The valid value is MONTH. */
  private IntervalEnum interval;

  /** Indicates whether the installment payment is available. */
  private Boolean enabled;
}
