/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PspCustomerInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PspCustomerInfo {

  /**
   * The name of Alipay+ payment methods. Note: This field is returned when Alipay+ payment methods
   * supports providing the related information. More information: Maximum length: 64 characters
   */
  private String pspName;

  /**
   * The customer ID of Alipay+ payment methods. Note: This field is returned when Alipay+ payment
   * methods supports providing the related information. More information: Maximum length: 64
   * characters
   */
  private String pspCustomerId;

  /**
   * The customer ID used for display. For example, loginId. Note: This field is returned when
   * Alipay+ payment methods supports providing the related information. More information: Maximum
   * length: 64 characters
   */
  private String displayCustomerId;

  private String displayCustomerName;

  private String customer2088Id;

  private String extendInfo;
}
