/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** PspCustomerInfo */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PspCustomerInfo {

  private String pspName;

  private String pspCustomerId;

  private String displayCustomerId;

  private String displayCustomerName;

  private String customer2088Id;

  private String extendInfo;
}
