/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import java.math.BigDecimal;
import lombok.*;

/** Quote */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Quote {

  private String quoteId;

  private String quoteCurrencyPair;

  private BigDecimal quotePrice;

  private String quoteStartTime;

  private String quoteExpiryTime;

  private Boolean guaranteed;
}
