/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** SettlementStrategy */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SettlementStrategy {

  /**
   * The ISO currency code of the currency that the merchant wants to settle against. This field is
   * required if the merchant signed up for multiple settlement currencies. Otherwise, the error
   * code,SETTLE_CONTRACT_NOT_MATCH, will be returned.
   */
  private String settlementCurrency;
}
