/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** SettlementStrategy */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SettlementStrategy {

  /**
   * The ISO currency code of the currency that the merchant wants to be settled against. The field
   * is required if the merchant signed up for multiple currencies to settle. More information:
   * Maximum length: 3 characters
   */
  private String settlementCurrency;
}
