/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.model.ams;

import lombok.*;

/** Shipping */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Shipping {

  private UserName shippingName;

  private Address shippingAddress;

  /**
   * The delivery service provider for shipping a physical product, such as FedEx, UPS, or USPS.
   * Note: Specify this parameter if you require risk control. Providing this information helps to
   * increase the accuracy of anti-money laundering and fraud detection, and increase payment
   * success rates. More information: Maximum length: 128 characters
   */
  private String shippingCarrier;

  /**
   * The phone number of a recipient (including extension). Specify this parameter when one of the
   * following conditions is met: You require risk control. The value of paymentMethodType is OVO
   * and you collect the phone number that is bound to the OVO account during the payment process.
   * Providing this information helps to increase the accuracy of anti-money laundering and fraud
   * detection, and increase payment success rates. More information: Maximum length: 16 characters
   */
  private String shippingPhoneNo;

  /**
   * The email address where virtual goods are sent. Specify this parameter when one of the
   * following conditions is met: if you require risk control. if you are a digital and
   * entertainment merchant. Providing this information helps to increase fraud and identity theft
   * detection. More information: Maximum length: 64 characters
   */
  private String shipToEmail;

  private String shippingFeeId;

  private Amount shippingFee;

  private String shippingDescription;

  private DeliveryEstimate deliveryEstimate;
}
