templateDir: ./templates/libraries/jersey3
files:
#  api_single.mustache:
#    folder: api
#    templateType: API
#    destinationFilename: Single.java
additionalProperties:
  isRequestClass: 
    type: boolean
    value: "classname.matches('^.*Request$')"