/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.alipay.global.api.response.ams.pay;

import com.alipay.global.api.model.ams.*;
import com.alipay.global.api.model.ams.AcquirerInfo;
import com.alipay.global.api.model.ams.Amount;
import com.alipay.global.api.model.ams.ChallengeActionForm;
import com.alipay.global.api.model.ams.PspCustomerInfo;
import com.alipay.global.api.model.ams.Quote;
import com.alipay.global.api.model.ams.RedirectActionForm;
import com.alipay.global.api.response.AlipayResponse;
import java.util.List;
import lombok.*;

/** AlipayPayResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPayResponse extends AlipayResponse {

  private String paymentRequestId;

  private String paymentId;

  private Amount paymentAmount;

  private String paymentData;

  private Amount actualPaymentAmount;

  private Quote paymentQuote;

  private String paymentTime;

  private String paymentCreateTime;

  private String authExpiryTime;

  private Amount nonGuaranteeCouponValue;

  private String paymentActionForm;

  private PspCustomerInfo pspCustomerInfo;

  private ChallengeActionForm challengeActionForm;

  private RedirectActionForm redirectActionForm;

  private String orderCodeForm;

  private Amount grossSettlementAmount;

  private Quote settlementQuote;

  private String extendInfo;

  private String normalUrl;

  private String schemeUrl;

  private String applinkUrl;

  private String appIdentifier;

  private PaymentResultInfo paymentResultInfo;

  private AcquirerInfo acquirerInfo;

  private List<PromotionResult> promotionResult;
}
