/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.antom.model;

import lombok.*;

/** Address */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Address {

  private String region;

  private String state;

  private String city;

  private String address1;

  private String address2;

  private String zipCode;

  private String label;
}
