/*
 * Payment API
 * Payment API is used for xxx. Refer [doc](https://global.alipay.com/docs/ac/ams/consult) # Auth
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.antom.model;

import com.antom.response.AlipayResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.*;

/** AlipayPayConsultResponse */
@EqualsAndHashCode(callSuper = true)
@Data
public class AlipayPayConsultResponse extends AlipayResponse {

  private List<PaymentOption> paymentOptions = new ArrayList<>();

  private List<PaymentMethodInfo> paymentMethodInfos = new ArrayList<>();

  private String extendInfo;
}
