name: Coveralls

on: [pull_request]

jobs:

  coveralls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build & Test
        run: mvn clean test -Dcheckstyle.skip=true
      - name: Build with Maven
        run: mvn test jacoco:report -Dcheckstyle.skip=true
      # 还不设计测试
      # - name: Coveralls Coverage Report Submission
      #  run: mvn clean test jacoco:report coveralls:report -Dcheckstyle.skip=true --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}
